version: "3"

vars:
  DEFCONFIG: anycubic_kobra_rockchip_rv1106g3_defconfig
env:
  BR2_EXTERNAL: "{{ .ROOT_DIR }}"

includes:
  make:
    taskfile: taskfile.make.yml
    dir: buildroot/

tasks:
  dependencies:
    desc: Prepare dependencies
    status:
      - test -d "{{ .BUILDROOT_DIR }}"
    cmds:
      - git submodule update --init
      - scripts/apply_fixes.sh

  sdk:
    cmds:
      - task: dependencies
      - task: make:sdk_defconfig
      - task: make:sdk

  default:
    desc: Build
    cmds:
      - task: dependencies
      - task: make:loaddefconfig
      - task: make:build